### ISSUE TITLE
i01 Web bug

### ISSUE THREAD

**Issue by CodeWriterWriter** [nodezoo/nodezoo-workshop#29]
attempting to run the web microservice returns the following error and crashes the process:
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::43000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1238:14)
    at listen (net.js:1274:10)
    at Server.listen (net.js:1370:5)
    at Seneca.api_repl (/Users/isaacmahon/Documents/nodezoo-web/node_modules/seneca/seneca.js:1391:8)
    at /Users/isaacmahon/Documents/nodezoo-web/srv/app-dev.js:13:8
    at module.exports (/Users/isaacmahon/Documents/nodezoo-web/app.js:77:3)
    at Object.<anonymous> (/Users/isaacmahon/Documents/nodezoo-web/srv/app-dev.js:4:14)
    at Module._compile (module.js:435:26)

**Comment by mcdonnelldean** [comment]
Killall node issue, covered in the readme updates coming.
